name: Snake Animation

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight
  workflow_dispatch:

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: Platane/snk@v2
        with:
          github_user: AymanSec  # Your GitHub username
          svg_out_path: output/github-snake-dark.svg  # Output path for the snake SVG
